Repository wuhan-support/frontend, pull requests merged in 2020-02, with the labels that each got.

#23 Release
  src/router/index.js
  src/views/supplies/Supplies.vue
Labels: size/XS

#24 Merge pull request #24 from ray26/dev
  .github/workflows/nodejs_docker.yml
Labels: size/S

#25 Release
  .github/workflows/nodejs_docker.yml
Labels: size/S

#26 Interface optimization
  src/views/Home.vue
  src/views/lists/Accommodations.vue
  src/views/roles/People.vue
  src/views/roles/Staff.vue
  src/views/roles/Volunteer.vue
  src/views/supplies/Supplies.vue
Labels: size/S

#27 Release
  package.json
  src/components/DataTable.vue
  src/main.js
  src/utils/geo.js
  src/views/lists/Accommodations.vue
  src/views/supplies/Supplies.vue
  yarn.lock
Labels: approved, size/L

#28 Release
  src/App.vue
  src/views/Home.vue
  src/views/supplies/Supplies.vue
Labels: approved, lgtm, size/M

#29 🙏
  src/App.vue
Labels: approved, size/XS

#30 Release
  public/index.html
  src/App.vue
  src/apis/api.js
  src/components/DataTable.vue
  src/components/FormItem.vue
  src/router/index.js
  src/views/Home.vue
  src/views/lists/PeopleAccommodations.vue
  src/views/supplies/SuppliesSubmission.vue
Labels: approved, lgtm, size/XL

#31 Release
  package.json
  public/index.html
  src/App.vue
  src/assets/logo/gray.svg
  src/assets/logo/red.svg
  src/components/DataTable.vue
  src/components/FormItem.vue
  src/router/index.js
  src/views/lists/Accommodations.vue
  src/views/lists/MedicalPlatforms.vue
  src/views/lists/PeopleAccommodations.vue
  src/views/lists/PsychologicalPlatforms.vue
  src/views/lists/RealTimeMsgs.vue
  src/views/supplies/Supplies.vue
  src/views/supplies/SuppliesSubmission.vue
  yarn.lock
Labels: approved, lgtm, size/XXL

#35 修复32 33
  src/views/lists/Accommodations.vue
  src/views/supplies/Supplies.vue
Labels: approved, lgtm, size/XS

#39 Release
  package.json
  src/App.vue
  src/assets/under-deploy.html
  src/components/HomeDescription.vue
  src/components/Paginator.vue
  src/locales/zh.json
  src/main.js
  src/router/index.js
  src/views/supplies/Supplies.vue
Labels: approved, lgtm, size/XL

#43 例行更新
  .gitignore
  public/index.html
  src/components/DataTable.vue
  src/components/Paginator.vue
  src/components/PlaceSelector.vue
  src/views/supplies/Supplies.vue
  vue.config.js
Labels: approved, size/L

#44 取消Critters优化，修复排版爆炸
  vue.config.js
Labels: approved, lgtm, size/XS

#46 修复排版爆炸
  package.json
  src/App.vue
  vue.config.js
Labels: approved, lgtm, size/S

#47 Create CommunitySubmission.vue
  src/views/supplies/CommunitySubmission.vue
Labels: lgtm, size/L

#48 Update index.js
  src/router/index.js
Labels: size/S

#49 Update CommunitySubmission.vue
  src/views/supplies/CommunitySubmission.vue
Labels: approved, lgtm, size/S

#50 Update README.md
  README.md
Labels: approved, lgtm, size/M

#51 Apply K8S automatically deploy
  .github/workflows/nodejs_docker.yml
  manifests/fe-deployment.yaml
  manifests/fe-service.yaml
Labels: approved, enhancement, lgtm, size/L

#52 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#53 src/views/CommunitySubmission.vue文件,我改了第42行的type类格式以及第84行的输入联系人(添加了点击…
  package.json
  src/apis/api.js
  src/components/FormItem.vue
  src/components/PlaceSelector.vue
  src/utils/Console.js
  src/views/supplies/CommunitySubmission.vue
  src/views/supplies/Supplies.vue
Labels: approved, lgtm, size/XXL

#61 fix(communitysupplies): fixed text and routing index
  src/App.vue
  src/router/index.js
  src/store/index.js
  src/utils/service.js
  src/views/supplies/CommunitySubmission.vue
Labels: approved, size/L

#62 fix(request): preloader
  src/utils/service.js
Labels: approved, size/S
